logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /home/packer/webapp/webapp.log
      record_log_file_path: true

  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    move_severity:
      type:   
      fields:
        severity:
          move_from: jsonPayload.level

  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity]
